namespace: xtal
name: workstation
version: 0.1.1
readme: README.md

authors:
- Spencer Smolen <mail@spencersmolen.com>

description: Roles to turn a fresh EL server install into a developer-friendly workstation for terminal-based, vim-intensive work flows

license:
- GPLv3

license_file: ''

tags:
  - x11
  - X
  - Xorg
  - dwm
  - window manager
  - gui
  - desktop
  - workstation
  - development

dependencies: {}

repository: http://github.com/xtalcloud/ansible-workstation-collection.git
documentation: http://github.com/xtalcloud/ansible-workstation-collection/blob/master/README.md
homepage: http://github.com/xtalcloud/ansible-workstation-collection
issues: http://github.com/xtalcloud/ansible-workstation-collection/issues
