---

- name: pkg | fontconfig
  package: name=fontconfig state=present

- name: pkg | mkfontscale tools
  package: name=mkfontscale state=present
  when: ansible_os_family == "RedHat"

- name: pkg | xfont_utils tools
  package: name=xfont_utils state=present
  when: ansible_os_family == "Debian"


- name: INSTALLING FONT FILES
  block:

  - name: Create specified fonts target directory
    ansible.builtin.file: path={{ font_dest_dir }} state=directory mode=0755

  - name: unarchive | TTF font file archive
    unarchive: src={{ font_archive_url }} dest={{ font_dest_dir }} remote_src=yes

  - name: fontconfig | mkfontdir
    command: mkfontdir {{ font_dest_dir }}

  - name: fontconfig | mkfontsize
    command: mkfontscale  {{ font_dest_dir }}

  - name: fontconfig | generate fc-cache
    command: fc-cache {{ font_dest_dir }}

  when: font_family != ""


- name: CONFIGURING FONTCONFIG
  block:

  - name: fontconfig | set system font(s)
    template: src=local.conf.j2 dest=/etc/fonts/local.conf

  - name: fontconfig | load local customization file during fontconfig init
    template: src=51-local.conf.j2 dest=/etc/fonts/conf.d/51-local.conf
