---
- hosts: workstations
  become: yes
  vars:
    terminal_emulator: st
    desktop_color: #151515
  roles:
    - role: xtal.workstation.epel
    - role: xtal.workstation.fontconfig
    - role: xtal.workstation.ksuperkey
    - role: xtal.workstation.dwm
      vars:
        - enable_compositing: true

